### ISSUE TITLE
Autoprefixer isnt working

### ISSUE THREAD

**Issue by Swizz** [egoist/vbuild#145]
Hi there,

I encounter a bug with autoprefixer, it seem never running.
I do not know how to tell you more about this issue, so, this is a step to reproduce.

---

Given this `.vue` file : 
```vue
<style>
  div {
    flex: 1;
    transform: rotate(90deg);
  }
</style>
```

and this minimal `vbuild.config.js`
```js
module.exports = (options) => ({
  autoprefixer: {
    browsers: ['chrome 25']
  }
})
```

The result of a build is : 
```css
div{flex:1;transform:rotate(90deg)}
```

But according to https://autoprefixer.github.io, the result for the given filter : `chrome 25` should be
```css
  div {
    -webkit-flex: 1;
            flex: 1;
    -webkit-transform: rotate(90deg);
            transform: rotate(90deg);
  }
```

Node and vbuild version :
```sh
> node -v                                                                    
v7.7.3
> vbuild -v
6.24.13
```

Cheers,
